### ISSUE TITLE
Is TestDataConfig required or optional?

### ISSUE THREAD

**Issue by RobertStroud** [longwa/build-test-data#105]
The documentation for the build-test-data plugin suggests that `TestDataConfig.groovy` is required - specifically, it says:

> For Grails 3.x, you will need to manually create a TestDataConfig.groovy 

The use of **will** implies that `TestDataConfig.goovy` is compulsory rather than optional - however, my understanding is that `TestDataConfig.groovy` is not required.

Please could you clarify this aspect of the documentation.

Thanks,

Robert

**Comment by longwa** [comment]
Clarified documentation. Thanks!
