### ISSUE TITLE
Java 7 compatibility

### ISSUE THREAD

**Issue by mlkristiansen** [longwa/build-test-data#108]
I am upgrading an application from Grails 2 to Grails 3 where your plugin is used.
We are currently required to run Java 7. From the looks of:
grails/buildtestdata/BuildTestDataGrailsPlugin : Unsupported major.minor version 52.0
your plugin was build with Java 8

Is it possible for you to build a Java 7 version of the plugin, to make it compliant with java 7 like Grails 3?

**Comment by longwa** [comment]
Yes, I didn't realize it was set to 1.8 compatibility. I have some other changes I will push out soon along with this change.

**Comment by longwa** [comment]
Fixed in 3.3.0
