### ISSUE TITLE
[Naming Suggestion] Rename trait BuildDataTest to BuildTestData.

### ISSUE THREAD

**Issue by HardikModha** [longwa/build-test-data#110]
I've been using this plugin to generate test data for my grails test cases and I must say this is very helpful.  

I just upgraded my grails-app to `v3.3.5` and so I also upgraded `build-test-data` to the latest (`v3.3.0`) version. It is working fine but I have one suggestion of renaming `BuildDataTest` trait. 

The name `BuildDataTest` doesn't read better, IMO. It would be great if you can rename it to `BuildTestData` (as the name of the plugin) says. It is more verbose than `BuildDataTest`. Also, the name `BuildTestData` is itself explanatory of what it intends to do. If you consider this then I would be more than happy to submit a PR. 

Thanks!

**Comment by zyro23** [comment]
i guess this one is a matter of taste. i think `BuildDataTest` aligns nicely with `DomainUnitTest`, `ServiceUnitTest`, etc.

**Comment by longwa** [comment]
Yeah, it was named `BuildDataTest` because Grails already has a trait called `DataTest` (that BTD extends). At this point, I think we'll just leave it although I do agree that `BuildTestData` has a certain ring to it.
