### ISSUE TITLE
Database not being populated

### ISSUE THREAD

**Issue by neojoda** [longwa/build-test-data#16]
If I create the Class Author with an id composite like:
```
static mapping = {
    id composite:['firstName','lastName']
}
```

the method build does not throw any error but the database is not being populated.

**Comment by longwa** [comment]
The flush behavior in unit tests is a side effect of the way that Grails mocks session behavior and not unique to using BTD. The same issues arise if you build the objects manually. This behavior is also much more consistent in Grails 2.4 and later, particularly in Spec tests where the lifecycle of the test is better defined.
