### ISSUE TITLE
build self relation domain parent is null fail

### ISSUE THREAD

**Issue by maplye** [longwa/build-test-data#28]
I have a domain Module like this:

    class Module {
        String code
        Module parent
    }

then I build a module and the parent is null.

    Module.build(parent:null)

but I got the error, java.lang.NullPointerException: Cannot invoke method buildCascadingSave() on null object.

I used the version is 2.1.2.

**Comment by longwa** [comment]
This is a fairly basic function that is part of the test suite. Would need more information to figure out this specific scenario. Closing.
