### ISSUE TITLE
Standalone without grails?

### ISSUE THREAD

**Issue by omayevskiy** [longwa/build-test-data#29]
Hello,

first of all big thanks you for developing of this plugin.

Since GORM can be used standalone:
https://spring.io/guides/gs/accessing-data-gorm/

Is there a way to use build-test-data standalone as well, without grails?

Thank you!

**Comment by restagner** [comment]
@tednaleid & @omayevskiy 

I realize that a lot of time has passed between the last comment and this current posting, but I was wondering if any more thought has gone into this.  I have a use case where this would be very useful.

**Comment by longwa** [comment]
@tednaleid is looking at a more modular replacement for build-test-data (named `spackle`) which may be much more decoupled from Grails itself. Given the way BTD works, it would take a decent refactor to support this properly and would likely require several breaking changes.
