### ISSUE TITLE
Automatically add `@Domain` annotations for both HibernateTextMixin and MongoDbTestMixin tests

### ISSUE THREAD

**Issue by tednaleid** [longwa/build-test-data#36]
Initial support for working with the `@HibernateTestMixin` is in the `master` branch, but it currently requires the user to add all the necessary `@Domain` annotations.  

This is unlike the current `@Build` annotation for non-hibernate tests, as that automatically does the equivalent of a `@Mock` annotation for whatever classes need it.

It was also mentioned by @lhotari on [this issue](https://github.com/tednaleid/build-test-data/pull/33#issuecomment-49353191) that grails 2.4 also adds a `@MongoDbTestMixin` that would be nice to support.

Best case scenario is that we use the same `@Build` annotation as normal, but detect if the user is using either a hibernate or mongo annotations (or maybe via some other marker to support other classes that want `@Domain` annotations?), and automatically adds `@Domain` calls for all necessary domain classes.

**Comment by longwa** [comment]
This was released in version 2.4.0. If using HibernateDomainMixin, @Build should automatically use @Domain annotation instead of @Mock.
