### ISSUE TITLE
id doesn't auto-increment when not default id field

### ISSUE THREAD

**Issue by hyland82** [longwa/build-test-data#37]
Hi,

If a domain object's id is mapped using the name attribute, it doesn't increment the id. e.g
<pre><code>
class Client {
   Long clientId

   static mapping = {
        id name: 'clientId'
   }

}
</code></pre>
So the following would fail:
<pre><code>
assert Client.build().clientId  != Client.build().clientId
</code></pre>

**Comment by longwa** [comment]
Build test data doesn't do anything specific with the Id as the Grails test framework is responsible for handling it. I don't see how this could be something BTD is doing wrong.
