### ISSUE TITLE
[bug] DomainInstanceBuilder tries to create properties with bindable: false

### ISSUE THREAD

**Issue by neoecos** [longwa/build-test-data#39]
i have the following constraint in a model `merchantToken(blank: false, nullable: true, bindable: false, unique: true)`, this property is added in the default constructor.

The idea is to build a read-only property assigned at creation time.

The DomainInstanceBuilder is trying to assign a value to that property, but that is happening only when trying to use the build() in BootStrap.groovy, I'm also using the build in tests and it works.

```
ERROR context.GrailsContextLoaderListener  - Error initializing the application: Exception occurred inside setter of co.tpaga.api.models.Merchant.merchantToken; nested exception is org.hibernate.PropertyAccessException: Exception occurred inside setter of co.tpaga.api.models.Merchant.merchantToken
Message: Exception occurred inside setter of co.tpaga.api.models.Merchant.merchantToken; nested exception is org.hibernate.PropertyAccessException: Exception occurred inside setter of co.tpaga.api.models.Merchant.merchantToken
    Line | Method
->>  242 | save                             in grails.buildtestdata.DomainInstanceBuilder
```

**Comment by longwa** [comment]
Actually, the more I think about this the more I think that the bindable constraint shouldn't really impact whether we set it by default. BTD is trying to setup test data and it's more of a one-off case that you just don't want a required field to be set. Bindability refers really to the ability for the data binder to overwrite that property, not to the fact that you want to default that property to something.

In a case where you are using BTD to build a non-bindable attribute and you want it to stay null, you can just explicitly set that property to null either in TestDataConfig or in the property map.

I'm going to revert this change.
