### ISSUE TITLE
Issue for -Dgrails.env=ci test-app :unit :integration

### ISSUE THREAD

**Issue by satan1999** [longwa/build-test-data#41]
Hi There

I import the plugin like this in buildconfig

test ":build-test-data:2.1.2", { export = false }

But if i test app with the command  test-app -Dgrails.env=ci test-app :unit :integration

The builder will throw exception in integration test but not unit test
Example :
.build() is applicable for argument types: (java.util.LinkedHashMap)

It looks like the builder is not injected into Domains in integration test when test-app with different env name

Cheers
Wallace

**Comment by longwa** [comment]
@satan1999 Any chance this is still something that needs investigation? I'm going through old tickets and trying to close out some things.
