### ISSUE TITLE
How I can run this plugin in Grails 2.3.11? 

### ISSUE THREAD

**Issue by joasgarcia** [longwa/build-test-data#46]
How I can run this plugin in Grails 2.3.11?

**Comment by longwa** [comment]
Please use version 2.2.3 for Grails 2.3.x and earlier, it should be functionally equivalent for the time being. Unfortunately, Grails 2.4 had some breaking changes to the test architecture and it made sense to modify build test data to fit the new architecture.

I believe we need to update the documentation to indicate the compatibility changes. Thanks for the reminder.

**Comment by longwa** [comment]
Updated the documentation to be more clear about required versions
