### ISSUE TITLE
Support build for anything that implements the Validateable trait

### ISSUE THREAD

**Issue by marcocarnazzo** [longwa/build-test-data#52]
build-test-data is a great public but it manages only domain classes.
I suppose it needs constraints to create values: so, why it cannot manages also @Validatable commands?

**Comment by longwa** [comment]
@marcocarnazzo Seems reasonable. I've never tried passing a command object as the constructor for the `DomainInstanceBuilder()` so I'm not sure if it satisfies all the constraints. We may be able to do a small amount of refactoring to make it work. The main thing would be that `build()` isn't really valid for a command object, only `buildWithoutSave()` makes sense.

**Comment by longwa** [comment]
I'm working on incorporating some changes in the 3.3 version that will allow anything that implements `trait Validateable` to be built by BTD.
