### ISSUE TITLE
Using the plugin from within scripts

### ISSUE THREAD

**Issue by YaroSpace** [longwa/build-test-data#53]
I would like to use the plugin from within a script that I run with `run-script` in the grails console.  

Unfortunately, I get `org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session`.

I am using Grails 2.4.4 with HIbernate 4.
Any hints?

**Comment by longwa** [comment]
How are you trying to use it? Are you creating a DomainInstanceBuilder() directly and calling build on it? I think I would need to see an example usage in the script to understand what would be needed. The plugin is fairly integrated with the Grails test framework so it doesn't surprise me that many of the requirements are not met in a build script.

Also, the script support is vastly different in 3.0, so no matter what we do here it will be for a legacy release so I'm not sure it will warrant a lot of attention.

**Comment by YaroSpace** [comment]
Basically I have a seed script to populate the db with initial data.
I was just trying to do `User.build()`

**Comment by YaroSpace** [comment]
I thought that perhaps `User.withSession { User.buld() }` would work, but no.

**Comment by longwa** [comment]
No longer valid for Grails 3.x and beyond.
