### ISSUE TITLE
Works in *ControllerIntTests but fails in others

### ISSUE THREAD

**Issue by vijeetgv** [longwa/build-test-data#55]
I'm working on upgrading a project from 1.3.6 to 2.5.1 (build test data from 1.1.1 to 2.4.0) but running into issues with non-controller int tests.

.build\* methods are used everywhere in many integration test cases. But when I do 

```
test-app integration:
```

the method runs well in all the tests suffixed with `*ControllerIntTests` but fails for others like `*ServiceTests` showing exceptions like:

```
groovy.lang.MissingMethodException: No signature of method: com.zub.Brand.buildLazy() is applicable for argument types: (java.util.LinkedHashMap) values: [[subdomain:googoo]]
    at org.grails.datastore.gorm.GormStaticApi.methodMissing(GormStaticApi.groovy:92)
    at com.zub.ProductKeywordSearcherServiceTests.testExactMatchOneFromSeveralProducts(ProductKeywordSearcherServiceTests.groovy:67)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:252)
    at junit.framework.TestSuite.run(TestSuite.java:247)
```

Anything I'm missing from my side or can there be any 'hack' I can do to get this running? Much appreciated.

**Comment by longwa** [comment]
For integration tests, the domain object should be annotated with the build* methods by default. Are your tests annotated with @TestMixin(IntegrationTestMixin)?

I assume the Brand domain class is just a normal domain class in the grails-app/domains path?

**Comment by vijeetgv** [comment]
Hi Aaron, 
Thanks for replying. No there's no test mixins for integration tests. We're adding them for unit tests though. And yes Brand domain class is a normal domain class. Only thing is its serializable & it has some *hasMany* relationships defined. BTW, we have been using this plugin for over a year & everything runs fine except for when we upgraded to grails 2.5.1 & build-test-data-2.4.0.

**Comment by vijeetgv** [comment]
BTW, this No such method exception is happening not just for Brand but all other domain class which are used in those pattern of integration tests too. Only the integration tests with class names suffixed with `*ControllerIntTests` have the method available. Thanks for checking through this!

**Comment by vijeetgv** [comment]
@longwa did you get a chance to look into this further?

**Comment by longwa** [comment]
This must be something specific to this project as we've used the plugin with Grails 2.5.5 for awhile with no issues. This mechanism is completely different in Grails 3.x and probably not worth revisiting at this point.
