### ISSUE TITLE
support for insertable/updateable:false

### ISSUE THREAD

**Issue by dwhitt-litle** [longwa/build-test-data#56]
Objects that have GORM `mapping` properties specifying `insertable:false` or `updatable:false` are not persisted using `build()` and, thus, subsequent calls to `get` do not find the object. Such a domain object might be used for read-only data that is not intended to be manipulated by the Grails application under test.

Consider:

```
class Book {
    static mapping {
        title insertable: false
        title updatatble: false
        author insertable: false
        author updatatble: false
    }
    String title
    String author
}
```

Instead of creating an object with:

```
Book.build(title: 'Dr. No', author: 'Ian Flemming')
```

A workaround such as this must be used where `validatable: false` can be specified:

```
new Book(title: 'Dr. No', author: 'Ian Flemming').save(failOnError: true, validate: false)
```

Is there a way to use `build()` to do the same thing?

UPDATE: This behavior is observed using build-test-data 2.2.3 with Grails 2.1.5.

**Comment by deflomu** [comment]
A little late to the game but maybe for others or maybe this issue can be closed: You could use `Book.buildWithoutSave(title: 'Dr. No', author: 'Ian Flemming').save(failOnError: true, validate: false)`
