### ISSUE TITLE
Wiki is able to be edited by anyone

### ISSUE THREAD

**Issue by robertsmieja** [longwa/build-test-data#61]
Not sure if that's intentional, but it usually isn't. 

The links are also mostly broken from the main wiki page located here: https://github.com/longwa/build-test-data/wiki

For example, the "Basic Usage" link is broken because it links to "https://github.com/longwa/build-test-data/wiki/BasicUsage" instead of "https://github.com/longwa/build-test-data/wiki/Basic-Usage"

**Comment by longwa** [comment]
Changed the security to collaborators only. Thanks!
