### ISSUE TITLE
No such property: application for class: grails.buildtestdata.BuildTestDataGrailsPlugin

### ISSUE THREAD

**Issue by rpalcolea** [longwa/build-test-data#64]
Using Grails `3.2.0.RC1` and `3.0.0` version of the plugin I get the following error during integration tests:

```groovy
Caused by: groovy.lang.MissingPropertyException: No such property: application for class: grails.buildtestdata.BuildTestDataGrailsPlugin
    at grails.buildtestdata.BuildTestDataGrailsPlugin$_closure1.doCall(BuildTestDataGrailsPlugin.groovy:32)
```

Full Stacktrace:

https://gist.github.com/rpalcolea/cf7be13d2cbbd803c05c4976540441f4

**Comment by gregopet** [comment]
Any chance of this fix being pulled into the main project and published?

**Comment by longwa** [comment]
Sorry guys, was gone for a week and then swamped when I got back. I'm gonna take a look today and try to get this merged.

**Comment by rpalcolea** [comment]
Thanks @longwa!

**Comment by gregopet** [comment]
Thank you!
