### ISSUE TITLE
does 'disabling' do anything?

### ISSUE THREAD

**Issue by yspotts** [longwa/build-test-data#75]
I'd like to disable the build-test-data plugin for production. Following the documentation, I added the following lines to the `TestDataConfig.groovy` file:

```
environments {
    production {
        testDataConfig {
            enabled = false
        }
    }
}
```

However, when I run my grails app, I see that the `build` methods are added to all my domain objects. Exploring the code, I came across this snippet:

```
...
        TestDataConfigurationHolder.loadTestDataConfig()

        if (!TestDataConfigurationHolder.isPluginEnabled()) {
            log.warn("build-test-data plugin is disabled in this environment")
        }

        log.debug('build-test-data plugin enabled, decorating domain classes with build methods')
...
```

It seems like if the plugin is marked `enabled=false` the only effect is a log statement, with the code dropping through to decorate the domain classes in any event. Am I missing something? Should there be a `return` statement in that `if` block? Is this a bug?

Thanks!

**Comment by longwa** [comment]
Definitely looks like a bug. However, in the newer version the disabling is removed anyway as traits are injected via a TraitInjector at compile time. I'm going to close this since it's not really relevant going forward.
