### ISSUE TITLE
executeQuery fails for unit test which implements HibernateSpec

### ISSUE THREAD

**Issue by tobisinghania** [longwa/build-test-data#77]
When I create a Spock unit test which extends HibernateSpec and add the @Build([MyDomain]) annotation to the test, calls to MyDomain.executeQuery(...) fail with

    String-based queries like [executeQuery] are currently not supported in this implementation of GORM. Use criteria instead.

but those calls succeed if I build the domain instance manually. I guess this happens, because @Build mocks the domain class, which it should no do when the unit test loads a database context.

Without the @Build annotation, I am not able to call the MyDomain.build() method.
I am using version 3.0.1 of the plugin.

**Comment by longwa** [comment]
Related to #71

**Comment by longwa** [comment]
Proper HibernateSpec support is in 3.3.0.
