### ISSUE TITLE
Plugin broken for 3.3.x line - java.lang.NoClassDefFoundError: org/grails/compiler/injection/test/TestForTransformation

### ISSUE THREAD

**Issue by sgates** [longwa/build-test-data#80]
Looks like grails 3.3 removed org.grails.compiler.injection.test.TestForTransformation because of the test subsystem rewrite. Not sure how big of a lift this is, but we cannot easily upgrade our apps to 3.3 without re-writing 400+ unit tests (because most rely on on this plugin!). 

Love the plugin, have used it for years, is this something that can be looked at? Thanks!

**Comment by sgates** [comment]
Just noticed in the new grails docs:
`
"To simplify upgrades you can can still use the previous AST transformation based framework by adding the following dependency to your Grails application:
build.gradle:
testCompile "org.grails:grails-test-mixins:3.3.0""
`

Just FYI for others, it doesn't look like the real 3.3.0 version is released yet, I could only find RC1:
testCompile "org.grails:grails-test-mixins:3.3.0.RC1"
Located here: https://repo.grails.org/grails/core/org/grails/grails-test-mixins/

I haven't been able to fully test if this magically fixes everything or not, will report back, but at least the app compiles now!

**Comment by sgates** [comment]
Looks like this is a pretty core part of the plugin - grails.buildtestdata.mixin.BuildTransformation implements TestForTransformation, and this seems pretty vital to the whole way in which the plugin functions. Looks like this mechanism would need to be rewritten for the new ControllerUnitTest<>/ServiceUnitTest<>/DomainUnitTest<> testing system, and I don't know enough about this or the plugin to offer a quick fix pull request. I might look into it a little deeper for fun, but this may be a significant amount of work.

**Comment by allnightlong** [comment]
Also run into this issue, while upgrading my app.
Takes pretty long time to figure out cause of the problem.

**Comment by longwa** [comment]
I'm working on a release for Grails 3.3x but it requires a good bit of rework and some changes to the way the plugin works. I'm hoping to have it done in the next week or so.

It will be a breaking change, switching to a Trait based system instead of using the annotations (similar to what Grails did).

**Comment by sgates** [comment]
Wow, that's awesome news! I was doing some workarounds on my own time, but this is way better. Thanks so much for the effort, you've saved many of us a TON of work. The trait based re-work is no big deal, we had to rework our tests for that anyway. I'll be keeping my eye on this, and looking forward to upgrading in the coming weeks!

**Comment by longwa** [comment]
@sgates I've been working with @tkvw to incorporate some of his ideas in https://github.com/tkvw/gorm-build-test-data. 

I think the final solution may end up being mostly backwards compatible with a few exceptions. I'm considering putting the compatibility stuff in a separate plugin to make it easier to separate the two of them; I haven't really settled on that yet.

Our project has a TON of BTD tests so I do like the idea of porting them slowly over time :)

**Comment by sgates** [comment]
@longwa that sounds great. Your plugin got a mention in the new Practical Grails 3 book - make sure to give Eric Helgeson a ping when you think the updates are up to snuff (if you're not in touch already) - he mentioned something about updating the book to grails 3.3 once BTD has been bumped. Cool stuff!

**Comment by longwa** [comment]
3.3.0.RC1 has been released for Grails 3.3.x and higher.

**Comment by sgates** [comment]
WOOOOOOOOO! Thanks! We'll begin testing it out.
