### ISSUE TITLE
Fix base tests and move main code base.

### ISSUE THREAD

**Issue by basejump** [longwa/build-test-data#87]
made all unit tests vs integration

**Comment by basejump** [comment]
@longwa let me know if you have some time to setup a chat. looks like you are working on this too. I have all but 4 tests passing with this latest PR

**Comment by basejump** [comment]
`gradle check` has all tests passing now under this PR https://github.com/longwa/build-test-data/pull/86

**Comment by basejump** [comment]
if base tests are unit tests the way they are structured in #86 then they can really be all moved under the main build-test-data project to make things cleaner.

**Comment by basejump** [comment]
add a PR to move tests and fix some of them

**Comment by longwa** [comment]
Ok, I had all of the tests working with your stuff merged in so we may be
ok.

**Comment by longwa** [comment]
Thanks for all the help! Once I get our main project ported to Grails 3.3
this month, I should be able to put this BTD through more paces.

I'm working on some updated AsciiDoc right now. I want to move to that for
the new stuff and just leave the legacy documentation on the GitHub Wiki
for now.

**Comment by basejump** [comment]
I can move your wiki real quick to our MD doc engine that uses mkdocs. We like it better. I'll put it up and you can take a look real quick to see if you like it. it what powers this https://yakworks.github.io/gorm-tools/

**Comment by basejump** [comment]
I am working on getting it working for the hibernateSpec right now. https://github.com/longwa/build-test-data/issues/71

**Comment by longwa** [comment]
I've pushed all the new docs as AsciiDoc if you wanna take those. They are
in the docs/ subfolder.

**Comment by longwa** [comment]
I found HibernateSpec to be worthless. Maybe it's better now but it used to
require that you registered anything that was part of the sub-graph you
were trying to build. For our project, we would end up bringing in 40 or 50
entities just to build one. It was easier to just use an IntegrationTest at
that point. Maybe that's not the case anymore.

**Comment by longwa** [comment]
I think the AsciiDoc looks pretty good, I might just stick with it:

http://longwa.github.io/build-test-data/index
