### ISSUE TITLE
support example constraint.

### ISSUE THREAD

**Issue by snimavat** [longwa/build-test-data#93]
If there is an example meta constraint on domain. Build test data should utilze the the value of constraint and use it.

Thoughts on how to handle the constraint value ? 
- Always expect value to be string and use type converters to convert to actual property type ?
- Or use the value as it is, and expect value to be of actual property type (eg date for a date type property) ?
  

```
class Book {
   String name
   Date datePublished
  
  static constraints = {
    name example: "test"
    datePublished example: "08/01/2018"
  }
}

```

**Comment by basejump** [comment]
Done during reorg. Will be in the next RC. see https://github.com/longwa/build-test-data/blob/master/plugin/src/test/groovy/basetests/ExampleDataSpec.groovy
